### ISSUE TITLE
what is this mod? no description

### ISSUE THREAD

**Issue by TheRanker** [nvb-uy/Create_Questing#2]
im trying to find details of whta the hell this mod is....  as its title and subtext is interesting...
but on cf... 
https://www.curseforge.com/minecraft/mc-mods/create-questing

your decription page is non existant.. cause discord removes images after a certain amount of time .. .due to storage capacity. 

cant coment there either... so... here we are.. 

please update your CF page.. so me and anyone else can find out what this mod is and hopefully how to use it.

**Comment by nvb-uy** [comment]
Fixed
