### ISSUE TITLE
No quests showing up

### ISSUE THREAD

**Issue by KaisDarkness** [nvb-uy/Create_Questing#4]
I have the mod loaded with create, but no quests are apparent when I look at my quests. It's just blank
![Uploading image_2024-07-12_093101143.png…]()

**Comment by nvb-uy** [comment]
Read what the mod does please. This mod does not add quests.

**Comment by nvb-uy** [comment]
You have to make the quests yourself, the mod does not add quests, it only adds a theme for FTB Quests

**Comment by KaisDarkness** [comment]
oh mb i thought it added quests. do you know any downloads for quests though?
